server:
  port: 8080

# Ciruit Breaker Endpoints:
# Landing Page: http://localhost:8080/hystrix
# Hystrix Dashboard: http://localhost:8080/actuator/hystrix.stream
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
      base-path: /actuator